### ISSUE TITLE
Support for 2500 series?

### ISSUE THREAD

**Issue by mythsmith** [wjasper/Linux_Drivers#10]
Is there any plan to support 2500 series (specifically 2527)? Is there any past experience, or any specific reason they were not implemented?

**Comment by wjasper** [comment]
I don;t have any immediate plans to support the USB-2500 series.  That board was originally designed by IO-Tech and not Measurement Computing who acquired them, and the whole paradigm does not lend itself  well to using libusb and running from user-space.

**Comment by mythsmith** [comment]
So do you have information/documentation about how it works?
