### ISSUE TITLE
Default values for DOut on USB1024 and possibly others.

### ISSUE THREAD

**Issue by stephendb** [wjasper/Linux_Drivers#14]
It does not appear to be possible to set DOut high before or during usbDConfigPort_USB1024LS. If your system uses low voltage as an On signal for relays then everything will turn on during Configuration since it appears to default to low.

Is there a way to change the default during config to high instead? This would be a desirable option for all of the DAQs in this library.

**Comment by wjasper** [comment]
In the user's guide on page 4-1 it says: 
All pins pulled up to Vs via 47k resistors (default), Selection available for pull down to ground.  Hardware selectable via zero ohm resistor.
Check with MCC on setting the pull up / pull down resistors on power up.
