### ISSUE TITLE
test-usb1608.c -> sdataOut[] is declared too long

### ISSUE THREAD

**Issue by trimitri** [wjasper/Linux_Drivers#2]
Dear Dr. Jasper,

thanks a lot for those drivers!

When using the _test-usb1608G.c_ progam, I found an error:
`sdataOut` is declared as being `[2*512]` long, but only the first half is used when testing the analog output scanning. This leads to garbage values being read and half-sine-half-garbage output on the oscilloscope.

When the declaration is changed to `uint16_t sdataOut[512]`, everything works fine for me.

Regards,
Franz Gutsch

**Comment by wjasper** [comment]
thanks for the email.  Fixed.
