### ISSUE TITLE
Recover 1208FS-Plus if disconnected?

### ISSUE THREAD

**Issue by ThePapaG** [wjasper/Linux_Drivers#27]
Hi @wjasper ,

I was wondering if you might have a code snippet to recover connection to the 1208FS-Plus if it is disconnected? I want to ensure that if the connection is lost with the device that I can regain control of the device, any ideas?

Thanks, Grant.

**Comment by wjasper** [comment]
Hi Grant,
This is more of a USB question than specific to the 1208FS-Plus.  If you just unplug the device from the the USB bus, the handle is stale.  Depending on exactly what happened, you need to close things down
(look at the 'e' option in the test code), and then restart everything over (The first first lines in test-usb1208FS-Plus).  You may need to put a watchdog timer in your code to check that the device is still responding if that is going to be an issue.
Good luck,
Warren
