### ISSUE TITLE
analog input scan not working in test-usb1208LS

### ISSUE THREAD

**Issue by Dan-Emutex** [wjasper/Linux_Drivers#3]
Hi

When I run test-usb1208LS, selecting menu option 'n' to test analog input scan appears to hang forever waiting for some results from the hardware device.  I haven't dug too deep yet, except to say that I've confirmed that its stuck in the do-while loop here: https://github.com/wjasper/Linux_Drivers/blob/master/USB/mcc-libusb/usb-1208LS.c#L343

It looks like hid_get_feature_report() in pmd.c is returning -1, but I haven't figured out why yet.  Calling hid_error() afterwards returns a NULL string.

Has anyone else encountered this issue?

Thanks,
-Dan

P.S. menu option 'i' to test analog input is working fine, so it seems that the USB connection to the 1208LS is ok.

**Comment by wjasper** [comment]
Dan,
I think feature reports are broken in hidapi.  That affects the 1208LS and the minilab. devices only.  The read use interrupt and bulk transfers.

**Comment by Dan-Emutex** [comment]
@wjasper Thanks for your response.  MCC confirmed the same, and advised me to use the 1208FS+ product instead to have the continuous sampling option available under Linux.

Perhaps this information could be added in the code, or perhaps the option could be removed?
