### ISSUE TITLE
What is the optimized count value when polling data continuously from USB1608G in 50KBps?

### ISSUE THREAD

**Issue by openedhardware** [wjasper/Linux_Drivers#4]
I am going to use the raspberry pi to poll analog input data from USB1608G device continuously in the speed of 50ksps.
 
In the Linux driver, you had developed, I found there is a function something like this:
```usbAInScanStart_USB1608G(libusb_device_handle *udev, uint32_t count, uint32_t retrig_count, double frequency,uint8_t options)```
- Is this correct to use this function to continuously poll data from USB1608G?
 If so, what is the maximum value of `count` parameter here?
- Should I use `burst` mode by setting the 1st bit of `options` to 1? or normal mode?
- How about the trigger? Should I use it or ignore it?

**Comment by openedhardware** [comment]
Any thought on this?

**Comment by wjasper** [comment]
Look at test-usb1608G.c for the "C" option for continuous sampling.  In that case, count=0 for continuous sampling.  You should ignore retrig_count (unless you want re-triggering)  Burst mode tries to sample all the channels at once.  For only one channel, burst mode has no effect.
