### ISSUE TITLE
found small typo

### ISSUE THREAD

**Issue by swainsoftware** [wjasper/Linux_Drivers#43]
https://github.com/wjasper/Linux_Drivers/blob/af69edd9d0be4dd58d80c332a934402893d3a0df/USB/python/usb_dioLS.py#L163

>>> %Run test-usb1024LS.py
  File "/home/pi/Downloads/Redlab/Linux_Drivers-master/USB/python/usb_dioLS.py", line 163
    rasie ValueError('MemRead: max count is 8')
                   ^
SyntaxError: invalid syntax

>>>

**Comment by wjasper** [comment]
Thanks for the email.  It's fixed in the next upgrade.
Best
Warren
