### ISSUE TITLE
Exception causes variable not found

### ISSUE THREAD

**Issue by jeffallen** [wjasper/Linux_Drivers#46]
Getting an exception in AInScanRead will cause a Python error when len(data) happens after. Here's a fix. I didn't put it in a PR because I don't have time right now to go update all the places this error is present. Sorry.

```
diff --git a/USB/python/usb_1608G.py b/USB/python/usb_1608G.py
index d562a98..710f761 100755
--- a/USB/python/usb_1608G.py
+++ b/USB/python/usb_1608G.py
@@ -435,12 +435,13 @@ class usb1608G(mccUSB):
     else:
       nSamples = self.count*(self.lastElement+1)

+    data = None
     try:
       data =  list(unpack('H'*nSamples, self.udev.bulkRead(libusb1.LIBUSB_ENDPOINT_IN | 6, int(2*nSamples), self.HS_DELAY)))
     except:
       print('AInScanRead: error in bulkRead.')

-    if len(data) != nSamples:
+    if data is not None and len(data) != nSamples:
       raise ValueError('AInScanRead: error in number of samples transferred.')
       return len(data)
```

**Comment by wjasper** [comment]
OK I'll put that in.  Do you know what caused the exception?

**Comment by wjasper** [comment]
Hi Jeff, thanks for the input.  I've updated most of the drivers with that logic.  I'm going to close out this comment.  Glad things are working for you.  The USB-1608G is a pretty reliable device.
Best,
Warren
