### ISSUE TITLE
PCI DAS-4020-12 Installation

### ISSUE THREAD

**Issue by ghassel** [wjasper/Linux_Drivers#6]
I am trying to install a PCI DAS 4020-12 board, and I received the following error message when I try to do the test:

/dev/das4020-12/ad0_0: No such file or directory
error opening device /dev/das4020-12/ad0_0

I was wondering if I need to do anything else to install the board?

**Comment by wjasper** [comment]
If you are running Ubuntu, check that the Comedi drivers are blacklisted as described in the README (FAQ near the bottom.  They may be conflicting with my driver.
