### ISSUE TITLE
USB Linux driver build error

### ISSUE THREAD

**Issue by jaythecelt** [wjasper/Linux_Drivers#7]
I'm writing an interface between a Raspberry Pi and a USB-2408-2AO.  I'm following this [tech tip](https://www.mccdaq.com/TechTips/TechTip-9.aspx) and ran across this error at step 6 under **Install the USB Linux driver and compile the test programs**:

gcc -g -Wall -fPIC -O -I/usr/local/include/libusb-1.0 -L/usr/local/lib -lusb-1.0                                  -c -o pmd.o pmd.c
pmd.c:172:5: error: conflicting types for ‘getUsbSerialNumber’
 int getUsbSerialNumber(libusb_device_handle *udev, unsigned char serial[])
     ^
In file included from pmd.c:25:0:
pmd.h:77:6: note: previous declaration of ‘getUsbSerialNumber’ was here
 void getUsbSerialNumber(libusb_device_handle *udev, unsigned char serial[]);
      ^
<builtin>: recipe for target 'pmd.o' failed
make: *** [pmd.o] Error 1

Here is the relevant part of the [session log showing the make messages.](https://github.com/wjasper/Linux_Drivers/files/1043576/log.txt)
It looks like this error was introduced with the latest push.

Thanks,
Jay

**Comment by wjasper** [comment]
Forgot to push out pmd.h.  Please pull it now, it should work for you.

**Comment by jaythecelt** [comment]
Works ... thanks a lot!
